server.port=8083
spring.application.name=appointment-service

spring.datasource.url=jdbc:postgresql://localhost:5432/appointmentdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

resilience4j.circuitbreaker.instances.doctorServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.doctorServiceCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.doctorServiceCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.doctorServiceCB.permitted-number-of-calls-in-half-open-state=3

resilience4j.retry.instances.patientRetry.max-attempts=3
resilience4j.retry.instances.patientRetry.wait-duration=2s
resilience4j.retry.instances.patientRetry.retry-exceptions=org.springframework.web.client.ResourceAccessException

logging.level.io.github.resilience4j=DEBUG
